sudo: required
services:
    - docker

before_install:
    - docker build -t adreizamartins/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true adreizamartins/docker-react npm run test

